version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agri-iot/php
    container_name: app_agri_iot
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    environment:
      SERVICE_NAME: app_agri_iot
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker_config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_agri_iot
    restart: unless-stopped
    tty: true
    ports:
      - "8900:80"
      - "4430:443"
    volumes:
      - ./:/var/www
      - ./docker_config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.25
    container_name: db_agri_iot
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel-event-conference-demo
      MYSQL_ROOT_PASSWORD: 123456a@
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker_config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
